apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-express-api-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-express-api   # <-- must match your Deployment name
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50   # scale out if avg CPU > 50%
